@startmindmap BASICS
<style>
node {
    MaximumWidth 150
    HorizontalAlignment left
}
</style>

+ 01. BASICS
++ 01.01 How Does the Internet Work
++ 01.02 HTTP
++ 01.03 Domain name
-- 01.04 DNS
-- 01.05 FTP
-- 01.06 How Do Web Browsers Work?

@endmindmap