@startmindmap BASICS
<style>
node {
    MaximumWidth 150
    HorizontalAlignment left
}
</style>

+  BASICS
-- 01 How Does the Internet Work
-- 02 HTTP
-- 03 Domain name
++ 04 DNS
++ 05 FTP
++ 06 How Do Web Browsers Work?

@endmindmap